export const navs_options = [
  {
    title: "Commodities",
    route: "/dashboard/fci",
  },
  {
    title: "Verify Farmer",
    route: "verify-farmer",
  },
  {
    title: "Verify Apmc Officer",
    route: "verify-apmc-officer",
  },
  {
    title: "APMCs",
    route: "apmcs",
  },
  {
    title: "Notifications",
    route: "notification",
  },
];

export const states = {
  AndhraPradesh: [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "West Godavari",
    "YSR Kadapa",
  ],
  ArunachalPradesh: [
    "Anjaw",
    "Changlang",
    "Dibang Valley",
    "East Kameng",
    "East Siang",
    "Lower Dibang Valley",
    "Lower Subansiri",
    "Papum Pare",
    "Siang",
    "Tawang",
    "Tirap",
    "Upper Siang",
    "West Kameng",
    "West Siang",
  ],
  Assam: [
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Darrang",
    "Dhemaji",
    "Dibrugarh",
    "Dima Hasao",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup",
    "Kamrup Metropolitan",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Marigaon",
    "Nagaon",
    "Nalbari",
    "Sivasagar",
    "South Salmara-Man Cachar",
    "Sonitpur",
    "Tamulpur",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong",
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhabua",
    "Bhojpur",
    "Bucharest",
    " Buxar",
    "Darbhanga",
    "East Champaran",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Kaimur",
    "Kangra",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Munger",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnia",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    " Saran",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali",
    "West Champaran",
  ],
  Chhattisgarh: [
    "Balod",
    "Balrampur",
    "Bastar",
    "Bemetara",
    "Bijapur",
    "Bilaspur",
    "Dantewada",
    "Dharmsinghgarh",
    "Durg",
    " Gariaband",
    "Gaurela-Pendra Marwahi",
    "Janjgir-Champa",
    "Jashpur",
    "Kabirdham",
    "Kondagaon",
    "Korba",
    "Koriya",
    "Mahasamund",
    "Mungeli",
    " Narayanpur",
    "Raigarh",
    "Rajnandgaon",
    "Sukma",
    "Surajpur",
    "Surguja",
  ],
  DadraAndNagarHaveli: ["Dadra", "Nagar Haveli"],
  DamanAndDiu: ["Daman", "Diu"],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Dang",
    "Devbhumi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagadh",
    "Kachchh",
    "Kamrej",
    "Kheda",
    "Mahsana",
    "Mahesana",
    "Maihar",
    "Morbi",
    "Narmada",
    "Navsari",
    "Panchmahal",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Tapi",
    "Vadodara",
    "Valsad",
  ],
  Haryana: [
    "Ambala",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurugram",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Nuh",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ],
  HimachalPradesh: [
    "Bilaspur",
    "Chamba",
    "Champawat",
    "Kangra",
    "Kinnaur",
    " Kullu",
    "Lahaul Spiti",
    " Mandi",
  ],
};

export const States = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const mandisList = [
  {
    state: "Maharashtra",
    mandis: [
      { title: "APMC-1", value: "APMC 1" },
      { title: "APMC-2", value: "APMC 2" },
      { title: "APMC-3", value: "APMC 3" },
      { title: "APMC-4", value: "APMC 4" },
      { title: "APMC-5", value: "APMC 5" },
      { title: "APMC-6", value: "APMC 6" },
    ],
  },
];

export const commodities = [
  "Wheat",
  "Rice",
  "Onion",
  "Potato",
  "Corn",
  "Cotton",
];

export const commodityprices = {
  Rice: { valinkg: 80, valinltr: 20 },
  Wheat: { valinkg: 40 },
  Corn: { valinkg: 20 },
  Cotton: { valinkg: 100 },
  Potato: { valinkg: 25 },
};

export const Commodities = [
  { title: "rice", value: "Rice" },
  { title: "wheat", value: "Wheat" },
  { title: "tur", value: "Tur" },
  { title: "soyabean", value: "Soyabean" },
  { title: "chana", value: "Chana" },
];

export const dashboardDetails = [
  {
    State: "Maharashtra",
    APMCS: "Pune",
    Commodity: "Onion",
    Price: 25,
    CommodityTraded: 1000, // Amount traded in kilograms
    Unit: "Kg",
    Date: "2024-03-01",
  },
  {
    State: "Gujarat",
    APMCS: "Ahmedabad",
    Commodity: "Potato",
    Price: 20,
    CommodityTraded: 800, // Amount traded in kilograms
    Unit: "Kg",
    Date: "2024-03-01",
  },
  {
    State: "Uttar Pradesh",
    APMCS: "Lucknow",
    Commodity: "Tomato",
    Price: 30,
    CommodityTraded: 1200, // Amount traded in kilograms
    Unit: "Kg",
    Date: "2024-03-01",
  },
  {
    State: "Karnataka",
    APMCS: "Bangalore",
    Commodity: "Rice",
    Price: 40,
    CommodityTraded: 1500, // Amount traded in kilograms
    Unit: "Kg",
    Date: "2024-03-01",
  },
  {
    State: "Punjab",
    APMCS: "Amritsar",
    Commodity: "Wheat",
    Price: 35,
    CommodityTraded: 1100, // Amount traded in kilograms
    Unit: "Kg",
    Date: "2024-03-01",
  },
  {
    State: "Tamil Nadu",
    APMCS: "Chennai",
    Commodity: "Mango",
    Price: 50,
    CommodityTraded: 2000, // Amount traded in kilograms
    Unit: "Kg",
    Date: "2024-03-01",
  },
];
export const detailsHeader = [
  { Header: "id", accessor: "0" },
  { Header: "APMCS", accessor: "7" },
  { Header: "Commodity", accessor: "1" },
  { Header: "CommodityTraded", accessor: "2" },
  { Header: "Price", accessor: "6" },
  { Header: "Unit", accessor: "3" },
  { Header: "Status", accessor: "11" },
];
